### PR TITLE
Fixed issue with slider panning.

### LINKED ISSUE #5: Index not changing correctly if you pan the slider in to place.
If you pan the slider all the way to the other label the setPressedHandler completion handler gets called but the index doesn't change.

Will checkout this issue a bit later and probably make a pull request.

### PR DESCRIPTION
**Pull request by Zhukn1**
This pull request resolves #5

### CODE REVIEW

**Comment by jagdevsendhav** [comment]
did you get any solution for slider panning index issue?. Still it is not working.

**Comment by Zhukn1** [comment]
This pull request fixes it. Try to clone my fork and check: git@github.com:Zhukn1/DVSwitch.git

**Comment by jagdevsendhav** [comment]
I did check out but I got  same issue.
I make below change in code:
 CGFloat minPos = 2 + self.sliderOffset;
 CGFloat maxPos = self.frame.size.width+2 - self.sliderOffset - self.sliderView.frame.size.width; 
Now it is working fine. is it correct?

**Comment by Zhukn1** [comment]
I noticed that there is a copy of the source files in the example project. I've updated them and now it works just fine. Check it out.

**Pull request merged**
